services:
  app:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ORIGIN=https://app.ewe.cz
      - NODE_OPTIONS=--max_old_space_size=4096
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "ms.ewe.cz:192.168.1.227"

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email senohrabeko@ewe.cz -d app.ewe.cz --agree-tos --non-interactive